name: Deployment

on: repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.REPOSITORY_PRIVATEKEY }}
          submodules: true
      - name: npm env
        run: npm install
        env:
          CI: true
      - name: hexo build
        run: |
          npx hexo clean
          npx hexo generate
        env:
          CI: true
      - name: test1
        run: |
          echo $REMOTE_HOST
          echo $REMOTE_USER
          echo $TARGET
      - name: test2
        run: |
          echo ${{REMOTE_HOST}}
          echo ${{REMOTE_USER}}
          echo ${{TARGET}}
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATEKEY }}
          # ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: $REMOTE_HOST
          REMOTE_USER: $REMOTE_USER
          TARGET: $TARGET
        
