name: Deployment

on: repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.REPOSITORY_PRIVATEKEY }}
          submodules: true
      - name: npm env
        run: npm install
        env:
          CI: true
      - name: hexo build
        run: |
          npx hexo clean
          npx hexo generate
        env:
          CI: true
      - name: test1
        run: |
          echo ${{ secrets.REMOTE_HOST }}
          echo ${{ secrets.REMOTE_USER }}
          echo ${{ secrets.TARGET }}
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATEKEY }}
          # ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
        
