name: Deployment

on: repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.REPOSITORY_PRIVATEKEY }}
          submodules: 'recursive'
      # - name: Initialize and update submodules
      #   run: |
      #     # 初始化子模块
      #     git submodule init
      #     # 更新子模块到最新提交
      #     git submodule update --recursive --remote
      - name: npm env
        run: npm install
        env:
          CI: true
      - name: hexo build
        run: |
          npx hexo clean
          npx hexo generate
        env:
          CI: true
      - name: Deploy
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATEKEY }}
          # ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: ${{ vars.TARGET }}
        
